language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     # You can uncomment this to explicitly choose an (old) version of the Arduino IDE
     #- ARDUINO_IDE_VERSION="1.8.10"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  # Note that every library should be installed in a seperate command
  - arduino --install-library "SparkFun CCS811 Arduino Library"
  - arduino --install-library "SparkFun BME280"
  - arduino --install-library "Adafruit GFX Library"
  - arduino --install-library "Adafruit PCD8544 Nokia 5110 LCD Library"
  - arduino --install-library "Arduino Low Power"
script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change
